// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: FetchSnContainingHu.sql

package database

import (
	"context"
)

const fetchSnContainingHandlingUnit = `-- name: FetchSnContainingHandlingUnit :many
SELECT DISTINCT sn FROM traces
WHERE hu = ?
`

func (q *Queries) FetchSnContainingHandlingUnit(ctx context.Context, hu string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, fetchSnContainingHandlingUnit, hu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sn string
		if err := rows.Scan(&sn); err != nil {
			return nil, err
		}
		items = append(items, sn)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
