// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: FetchCompleteBoardDataBySN.sql

package database

import (
	"context"
	"time"
)

const fetchBoardBySN = `-- name: FetchBoardBySN :many
SELECT id, traces.sn, traces.hu, ref_list, placed, boards.sn, pb, rev, comps.hu, pn, lot FROM traces
INNER JOIN boards ON traces.sn = boards.sn
INNER JOIN comps ON traces.hu = comps.hu
WHERE traces.sn = ?
`

type FetchBoardBySNRow struct {
	ID      int64
	Sn      string
	Hu      string
	RefList string
	Placed  time.Time
	Sn_2    string
	Pb      string
	Rev     string
	Hu_2    string
	Pn      string
	Lot     string
}

func (q *Queries) FetchBoardBySN(ctx context.Context, sn string) ([]FetchBoardBySNRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchBoardBySN, sn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchBoardBySNRow
	for rows.Next() {
		var i FetchBoardBySNRow
		if err := rows.Scan(
			&i.ID,
			&i.Sn,
			&i.Hu,
			&i.RefList,
			&i.Placed,
			&i.Sn_2,
			&i.Pb,
			&i.Rev,
			&i.Hu_2,
			&i.Pn,
			&i.Lot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
