// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Board struct {
	Sn  string
	Pb  string
	Rev string
}

type Comp struct {
	Hu  string
	Pn  string
	Lot string
}

type Trace struct {
	ID      int64
	Sn      string
	Hu      string
	RefList string
	Placed  time.Time
}
