// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StoreTraceData.sql

package database

import (
	"context"
	"time"
)

const storeTraceData = `-- name: StoreTraceData :exec
INSERT INTO traces (sn, hu, ref_list, placed)
VALUES (
    ?, ?, ?, ?
)
RETURNING id, sn, hu, ref_list, placed
`

type StoreTraceDataParams struct {
	Sn      string
	Hu      string
	RefList string
	Placed  time.Time
}

func (q *Queries) StoreTraceData(ctx context.Context, arg StoreTraceDataParams) error {
	_, err := q.db.ExecContext(ctx, storeTraceData,
		arg.Sn,
		arg.Hu,
		arg.RefList,
		arg.Placed,
	)
	return err
}
