// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StoreBoardData.sql

package database

import (
	"context"
)

const storeBoardData = `-- name: StoreBoardData :one
INSERT INTO boards (sn, pb, rev)
VALUES (
    ?, ?, ?
)
RETURNING sn, pb, rev
`

type StoreBoardDataParams struct {
	Sn  string
	Pb  string
	Rev string
}

func (q *Queries) StoreBoardData(ctx context.Context, arg StoreBoardDataParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, storeBoardData, arg.Sn, arg.Pb, arg.Rev)
	var i Board
	err := row.Scan(&i.Sn, &i.Pb, &i.Rev)
	return i, err
}
