// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StoreCompData.sql

package database

import (
	"context"
)

const storeCompData = `-- name: StoreCompData :exec
INSERT INTO comps (hu, pn, lot)
VALUES (
    ?, ?, ?
)
RETURNING hu, pn, lot
`

type StoreCompDataParams struct {
	Hu  string
	Pn  string
	Lot string
}

func (q *Queries) StoreCompData(ctx context.Context, arg StoreCompDataParams) error {
	_, err := q.db.ExecContext(ctx, storeCompData, arg.Hu, arg.Pn, arg.Lot)
	return err
}
