// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StoreTraceData.sql

package database

import (
	"context"
	"time"
)

const storeTraceData = `-- name: StoreTraceData :one
INSERT INTO traces (sn, hu, ref_list, placed)
VALUES (
    ?, ?, ?, ?
)
RETURNING id, sn, hu, ref_list, placed
`

type StoreTraceDataParams struct {
	Sn      string
	Hu      string
	RefList string
	Placed  time.Time
}

func (q *Queries) StoreTraceData(ctx context.Context, arg StoreTraceDataParams) (Trace, error) {
	row := q.db.QueryRowContext(ctx, storeTraceData,
		arg.Sn,
		arg.Hu,
		arg.RefList,
		arg.Placed,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.Sn,
		&i.Hu,
		&i.RefList,
		&i.Placed,
	)
	return i, err
}
