// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: StoreCompData.sql

package database

import (
	"context"
)

const storeCompData = `-- name: StoreCompData :one
INSERT INTO comps (hu, pn, lot)
VALUES (
    ?, ?, ?
)
RETURNING hu, pn, lot
`

type StoreCompDataParams struct {
	Hu  string
	Pn  string
	Lot string
}

func (q *Queries) StoreCompData(ctx context.Context, arg StoreCompDataParams) (Comp, error) {
	row := q.db.QueryRowContext(ctx, storeCompData, arg.Hu, arg.Pn, arg.Lot)
	var i Comp
	err := row.Scan(&i.Hu, &i.Pn, &i.Lot)
	return i, err
}
