// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testquerry.sql

package database

import (
	"context"
)

const fetchBoards = `-- name: FetchBoards :many
SELECT sn, pb, rev FROM boards
`

func (q *Queries) FetchBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, fetchBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(&i.Sn, &i.Pb, &i.Rev); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
