// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: WipeDB.sql

package database

import (
	"context"
)

const deleteBoards = `-- name: DeleteBoards :exec
DELETE FROM boards
`

func (q *Queries) DeleteBoards(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBoards)
	return err
}

const deleteComps = `-- name: DeleteComps :exec
DELETE from comps
`

func (q *Queries) DeleteComps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteComps)
	return err
}

const deleteTraces = `-- name: DeleteTraces :exec
DELETE FROM traces
`

func (q *Queries) DeleteTraces(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTraces)
	return err
}
